### ISSUE TITLE
Errors loading and import source code

### ISSUE THREAD

**Issue by rayanmargham** [this-is-bennyk/Funkin-VR#1]
# Errors when loading source code.
When attempting to load the source code even on high end pcs godot hangs.
theres a bunch of errors displayed in godot's debug console
![image](https://user-images.githubusercontent.com/69608259/132197078-724d4987-115e-488c-b6f6-54cb0715047c.png)
# How to make issue occur
download the source code of github
import it using godot
watch the errors flood in.

**Comment by TNT-King** [comment]
I am really noob at godot but you can try to install the plugins that the developers are using and you need to ask them what plugins they are using. If that doen't help then IDK

**Comment by this-is-bennyk** [comment]
Pre-v8 issue, please try again with the latest version of FNFVR
