### ISSUE TITLE
Can I Feature This On Godot From Source

### ISSUE THREAD

**Issue by PokeyManatee4** [this-is-bennyk/Funkin-VR#2]
_Can I Feature This On Godot From Source Please

**Comment by PokeyManatee4** [comment]
Close

**Comment by PokeyManatee4** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/b6d0de0a-0762-418e-9db2-b84c3ef51251-11611bb8-08a0-4a48-a006-f38848586588-v1.png?transparent=1&palette=1&width=246)

**Comment by this-is-bennyk** [comment]
Yes
