### ISSUE TITLE
quest version bugging out

### ISSUE THREAD

**Issue by XxsjrapsxX** [this-is-bennyk/Funkin-VR#4]
not sure ho else to describe it i will attach a video[

https://user-images.githubusercontent.com/44506272/156892256-143c072d-aed1-449b-a3c5-ee96ff40001c.mp4

](url)
fps was horrible and geometery was everywhere im on questfps was horrible and geometery was everywhere im on quest 2 btw

**Comment by XxsjrapsxX** [comment]
https://streamable.com/bhekno
video seemed to not work so i took another hope this upload works for rvideo seemed to not work so i took another hope this upload works for real this time

**Comment by this-is-bennyk** [comment]
Pre-v8 issue, please try again with the latest version of FNFVR
